name: minera_clockin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.11.0
  flutter_dotenv: ^6.0.1
  shared_preferences: ^2.5.5
  image_picker: ^1.2.3
  geolocator: ^14.0.2
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  excel: ^4.0.6
  pdf: ^3.11.3
  printing: ^5.13.4
  path_provider: ^2.1.5
  share_plus: ^13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - .env

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/minera.png"